corpus_name: ssi_unesco
corpus_pattern: '*.zip'
corpus_type: 1
language: english
pipelines:
  tagged_frame_pipeline: penelope.pipeline.spacy.pipelines.to_tagged_frame_pipeline
pipeline_payload:
  source: legal_instrument_corpus.zip
  document_index_source: legal_instrument_index.csv
  document_index_sep: ;
  filenames: null
  memory_store:
    lang: en
    lemma_column: lemma_
    pos_column: pos_
    spacy_model: en_core_web_sm
    tagger: spaCy
    text_column: text
  pos_schema_name: Universal
tagged_tokens_filter_opts:
  data:
    is_alpha: null
    is_digit: null
    is_punct: false
    is_stop: null
text_reader_opts:
  as_binary: false
  filename_fields:
  - unesco_id:_:2
  - year:_:3
  - city:\w+\_\d+\_\d+\_\d+\_(.*)\.txt
  filename_filter: null
  filename_pattern: '*.txt'
  index_field: null
